//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_Version.DB_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DauSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DauSach()
        {
            this.CuonSaches = new HashSet<CuonSach>();
        }
    
        public string MaSach { get; set; }
        public string TuaSach { get; set; }
        public string MaNXB { get; set; }
        public string MaTG { get; set; }
        public Nullable<int> GiaMua { get; set; }
        public Nullable<int> GiaMuon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuonSach> CuonSaches { get; set; }
        public virtual NXB NXB { get; set; }
        public virtual TacGia TacGia { get; set; }
    }
}
