//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_Version.DB_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muon
    {
        public string MaCuon { get; set; }
        public string MaKH { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<System.DateTime> HanTra { get; set; }
        public Nullable<int> TienPhat { get; set; }
        public bool DangMuon { get; set; }
        public bool DaThanhToan { get; set; }
    
        public virtual CuonSach CuonSach { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
